name: CMake test matrix
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [g++, clang++]
        kokkos: [on, off]
        mempool: [on, off]
        mpi: [on, off]
        exclude:
        - kokkos: off
          mempool: on

    env:
      CXX: ${{matrix.compiler.CXX}}
      MPICH_CXX: ${{matrix.compiler.CXX}}

    steps:
    - name: set mpi compiler wrapper
      if: ${{ matrix.mpi == 'on' }}
      run: |
           printf "0.1 %s\n" "${{env.CXX}}"
           echo "CXX=mpicxx" >> "$GITHUB_ENV"
           printf "0.2 %s\n" "${{env.CXX}}"
