name: CMake test matrix
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [g++, clang++]
        mpi: [on, off]

    env:
      compiler: foobar
      CXX: ${{matrix.compiler.CXX}}
      MPICH_CXX: ${{matrix.compiler.CXX}}

    steps:
    - name: set mpi compiler wrapper
      if: ${{ matrix.mpi == 'on' }}
      run: |
           env
           printf "0.1 %s %s\n" "$CXX" "$compiler"
           echo "CXX=mpicxx" >> "$GITHUB_ENV"
           printf "0.2 %s\n" "$CXX"
           env
